/**
 * APIClientSynthesizer
 *
 * API clients are NOT generated by create-vc-app.
 * This synthesizer creates them based on entity structure.
 */

import fs from "node:fs/promises";
import path from "node:path";

export interface APIClientOptions {
  /**
   * Project working directory
   */
  cwd: string;

  /**
   * Module name
   */
  moduleName: string;

  /**
   * Entity name (singular)
   */
  entityName: string;

  /**
   * Base API URL (optional)
   */
  baseUrl?: string;
}

export interface APIClientResult {
  /**
   * Path to API client file
   */
  clientPath: string;

  /**
   * Success flag
   */
  success: boolean;

  /**
   * Error if failed
   */
  error?: string;
}

/**
 * APIClientSynthesizer
 *
 * Creates API client files for modules.
 * NOTE: create-vc-app does NOT generate API clients, so we create them here.
 */
export class APIClientSynthesizer {
  /**
   * Generate API client file
   */
  async synthesize(options: APIClientOptions): Promise<APIClientResult> {
    try {
      const clientPath = this.getClientPath(options);

      // Ensure api directory exists
      const apiDir = path.dirname(clientPath);
      await fs.mkdir(apiDir, { recursive: true });

      // Generate API client content
      const content = this.generateClientContent(options);

      // Write file
      await fs.writeFile(clientPath, content, "utf-8");

      // Update api/index.ts to export the client
      await this.updateApiIndex(options);

      return {
        clientPath,
        success: true,
      };
    } catch (error) {
      return {
        clientPath: "",
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }

  /**
   * Generate API client content
   */
  private generateClientContent(options: APIClientOptions): string {
    const EntityName = this.capitalize(options.entityName);
    const entityPlural = this.pluralize(options.entityName);

    return `/**
 * ${EntityName} API Client
 *
 * Generated by AI Codegen
 */

import { useApiClient } from "@vc-shell/framework";

export interface ${EntityName} {
  id: string;
  name: string;
  // TODO: Add your entity properties here
  createdAt?: string;
  updatedAt?: string;
}

export interface ${EntityName}SearchQuery {
  keyword?: string;
  skip?: number;
  take?: number;
  sort?: string;
  // TODO: Add your search filters here
}

export interface ${EntityName}SearchResult {
  results: ${EntityName}[];
  totalCount: number;
}

export function use${EntityName}sClient() {
  const { getApiClient } = useApiClient("${entityPlural}");
  const client = getApiClient();

  return {
    /**
     * Search ${entityPlural}
     */
    async search(query: ${EntityName}SearchQuery): Promise<${EntityName}SearchResult> {
      // TODO: Replace with your actual API endpoint
      const response = await client.get("/${entityPlural}", { params: query });
      return response.data;
    },

    /**
     * Get ${options.entityName} by ID
     */
    async get(id: string): Promise<${EntityName}> {
      // TODO: Replace with your actual API endpoint
      const response = await client.get(\`/${entityPlural}/\${id}\`);
      return response.data;
    },

    /**
     * Create new ${options.entityName}
     */
    async create(data: Partial<${EntityName}>): Promise<${EntityName}> {
      // TODO: Replace with your actual API endpoint
      const response = await client.post("/${entityPlural}", data);
      return response.data;
    },

    /**
     * Update ${options.entityName}
     */
    async update(id: string, data: Partial<${EntityName}>): Promise<${EntityName}> {
      // TODO: Replace with your actual API endpoint
      const response = await client.put(\`/${entityPlural}/\${id}\`, data);
      return response.data;
    },

    /**
     * Delete ${options.entityName}
     */
    async delete(id: string): Promise<void> {
      // TODO: Replace with your actual API endpoint
      await client.delete(\`/${entityPlural}/\${id}\`);
    },
  };
}
`;
  }

  /**
   * Update api/index.ts to export the client
   */
  private async updateApiIndex(options: APIClientOptions): Promise<void> {
    const modulePath = path.join(options.cwd, "src", "modules", options.moduleName);
    const indexPath = path.join(modulePath, "api", "index.ts");

    const EntityName = this.capitalize(options.entityName);
    const exportStatement = `export * from "./${options.entityName}.client";\n`;

    try {
      // Read existing index
      let content = await fs.readFile(indexPath, "utf-8");

      // Check if export already exists
      if (!content.includes(exportStatement)) {
        content += exportStatement;
        await fs.writeFile(indexPath, content, "utf-8");
      }
    } catch {
      // Create index.ts if it doesn't exist
      await fs.writeFile(indexPath, exportStatement, "utf-8");
    }
  }

  /**
   * Get API client file path
   */
  private getClientPath(options: APIClientOptions): string {
    const modulePath = path.join(options.cwd, "src", "modules", options.moduleName);
    return path.join(modulePath, "api", `${options.entityName}.client.ts`);
  }

  /**
   * Capitalize string
   */
  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Pluralize entity name (simple version)
   */
  private pluralize(str: string): string {
    if (str.endsWith("y")) {
      return str.slice(0, -1) + "ies";
    }
    if (str.endsWith("s")) {
      return str + "es";
    }
    return str + "s";
  }
}
