/**
 * LocaleSynthesizer
 *
 * Locales are already generated by create-vc-app!
 * This class only modifies them if needed to add custom translations.
 */

import fs from "node:fs/promises";
import path from "node:path";

export interface LocaleOptions {
  /**
   * Project working directory
   */
  cwd: string;

  /**
   * Module name
   */
  moduleName: string;

  /**
   * Entity name
   */
  entityName: string;

  /**
   * Locale code (default: "en")
   */
  locale?: string;

  /**
   * Additional translations to add
   */
  customTranslations?: Record<string, any>;
}

export interface LocaleResult {
  /**
   * Path to locale file
   */
  localePath: string;

  /**
   * Success flag
   */
  success: boolean;

  /**
   * Error if failed
   */
  error?: string;
}

/**
 * LocaleSynthesizer
 *
 * Modifies locale files generated by create-vc-app.
 * Does NOT generate locales from scratch - they're already created by create-vc-app!
 */
export class LocaleSynthesizer {
  /**
   * Modify existing locale file with custom translations
   */
  async synthesize(options: LocaleOptions): Promise<LocaleResult> {
    try {
      const locale = options.locale || "en";
      const localePath = this.getLocalePath(options, locale);

      // Check if locale exists (should be created by create-vc-app)
      try {
        await fs.access(localePath);
      } catch {
        return {
          localePath,
          success: false,
          error: `Locale file not found at ${localePath}. It should be created by create-vc-app first.`,
        };
      }

      // Read locale file
      const content = await fs.readFile(localePath, "utf-8");
      const translations = JSON.parse(content);

      // Add custom translations if provided
      if (options.customTranslations) {
        this.mergeTranslations(translations, options.customTranslations);

        // Write updated translations
        await fs.writeFile(localePath, JSON.stringify(translations, null, 2), "utf-8");
      }

      return {
        localePath,
        success: true,
      };
    } catch (error) {
      return {
        localePath: "",
        success: false,
        error: error instanceof Error ? error.message : String(error),
      };
    }
  }

  /**
   * Merge custom translations into existing translations
   */
  private mergeTranslations(target: Record<string, any>, source: Record<string, any>): void {
    for (const [key, value] of Object.entries(source)) {
      if (typeof value === "object" && !Array.isArray(value)) {
        if (!target[key] || typeof target[key] !== "object") {
          target[key] = {};
        }
        this.mergeTranslations(target[key], value);
      } else {
        target[key] = value;
      }
    }
  }

  /**
   * Get locale file path
   */
  private getLocalePath(options: LocaleOptions, locale: string): string {
    const modulePath = path.join(options.cwd, "src", "modules", options.moduleName);
    return path.join(modulePath, "locales", `${locale}.json`);
  }
}
