import { IProductResponse } from "../../types";

export async function mockedProducts(): Promise<IProductResponse> {
  return Promise.resolve({
    totalCount: 40,
    results: [
      {
        id: 1,
        image: "/assets/1.jpg",
        gtin: "123456",
        sellerName: "Product 1",
        category: "Electronics",
        createdDate: "2021-08-21",
        status: "Draft",
      },
      {
        id: 2,
        image: "/assets/2.jpg",
        gtin: "123456",
        sellerName: "Product 2",
        category: "Electronics",
        createdDate: "2021-08-22",
        status: "Draft",
      },
      {
        id: 3,
        image: "/assets/3.jpg",
        gtin: "123456",
        sellerName: "Product 3",
        category: "Electronics",
        createdDate: "2021-08-23",
        status: "Draft",
      },
      {
        id: 4,
        image: "/assets/4.jpg",
        gtin: "123456",
        sellerName: "Product 4",
        category: "Electronics",
        createdDate: "2021-08-24",
        status: "Draft",
      },
      {
        id: 5,
        image: "/assets/5.jpg",
        gtin: "123456",
        sellerName: "Product 5",
        category: "Electronics",
        createdDate: "2021-08-25",
        status: "Draft",
      },
      {
        id: 6,
        image: "/assets/1.jpg",
        gtin: "123456",
        sellerName: "Product 6",
        category: "Electronics",
        createdDate: "2021-08-21",
        status: "Draft",
      },
      {
        id: 7,
        image: "/assets/2.jpg",
        gtin: "123456",
        sellerName: "Product 7",
        category: "Electronics",
        createdDate: "2021-08-22",
        status: "Draft",
      },
      {
        id: 8,
        image: "/assets/3.jpg",
        gtin: "123456",
        sellerName: "Product 8",
        category: "Electronics",
        createdDate: "2021-08-23",
        status: "Draft",
      },
      {
        id: 9,
        image: "/assets/4.jpg",
        gtin: "123456",
        sellerName: "Product 9",
        category: "Electronics",
        createdDate: "2021-08-24",
        status: "Draft",
      },
      {
        id: 10,
        image: "/assets/5.jpg",
        gtin: "123456",
        sellerName: "Product 10",
        category: "Electronics",
        createdDate: "2021-08-25",
        status: "Draft",
      },
    ],
  });
}
