FROM nginx:alpine

RUN rm /usr/share/nginx/html/index.html \
    && apk update && apk add -u gettext

COPY ./apps/vendor-portal/dist /usr/share/nginx/html
COPY ./.dockerfiles/platform-manager-demo/nginx.default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
