import fs from "node:fs/promises";
import path from "node:path";
import { globby } from "globby";
import { hasAutoGeneratedMarker } from "../transformer/header.js";
import type { OrphanEntry } from "../types.js";

export async function findOrphans(targetRoot: string, syncedRelPaths: Set<string>): Promise<OrphanEntry[]> {
  const files = await globby(["**/*.md"], { cwd: targetRoot, absolute: false });
  const out: OrphanEntry[] = [];
  for (const rel of files) {
    if (syncedRelPaths.has(rel)) continue;
    const content = await fs.readFile(path.join(targetRoot, rel), "utf8");
    if (hasAutoGeneratedMarker(content)) {
      out.push({ target: rel });
    }
  }
  return out;
}
