export const AUTO_GEN_MARKER = "AUTO-GENERATED FROM vc-shell — DO NOT EDIT MANUALLY";

export function prependAutoGeneratedHeader(body: string, sourceRelPath: string): string {
  const header = [
    `<!-- ${AUTO_GEN_MARKER} -->`,
    `<!-- Source: ${sourceRelPath} -->`,
    `<!-- To update: edit the source file in vc-shell, then run yarn docs:sync -->`,
  ].join("\n");
  return `${header}\n\n${body}`;
}

export function hasAutoGeneratedMarker(content: string): boolean {
  return content.includes(AUTO_GEN_MARKER);
}
