import { stripInternalBlocks } from "./strip-internal.js";
import { expandStorybookDirectives } from "./storybook-directive.js";
import { rewriteCrossDocLinks } from "./links.js";
import { prependAutoGeneratedHeader } from "./header.js";

export interface TransformContext {
  sourceRelPath: string; // path shown in AUTO-GENERATED header
  sourcePath: string; // for resolveTarget lookups
  targetPath: string; // relative inside vc-docs
  storybookUrl: string;
  knownStoryIds: Set<string>;
  resolveTarget(sourcePath: string, href: string): string | null;
}

export function runTransformPipeline(body: string, ctx: TransformContext): string {
  let out = body;
  out = stripInternalBlocks(out);
  out = expandStorybookDirectives(out, {
    storybookUrl: ctx.storybookUrl,
    knownIds: ctx.knownStoryIds,
    sourcePath: ctx.sourcePath,
  });
  out = rewriteCrossDocLinks(out, {
    sourcePath: ctx.sourcePath,
    targetPath: ctx.targetPath,
    resolveTarget: ctx.resolveTarget,
  });
  out = prependAutoGeneratedHeader(out, ctx.sourceRelPath);
  return out;
}
