FROM nginx:alpine

RUN rm /usr/share/nginx/html/index.html \
    && apk update && apk add -u gettext

COPY ./packages/ui-kit/storybook-static /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]