import { describe, it, expect } from "vitest";
import { prependAutoGeneratedHeader, hasAutoGeneratedMarker, AUTO_GEN_MARKER } from "../src/transformer/header.js";

describe("prependAutoGeneratedHeader", () => {
  it("adds three-line HTML comment header pointing back at source", () => {
    const out = prependAutoGeneratedHeader("# Title", "framework/ui/foo.docs.md");
    expect(out.startsWith("<!--")).toBe(true);
    expect(out).toContain(AUTO_GEN_MARKER);
    expect(out).toContain("Source: framework/ui/foo.docs.md");
    expect(out).toContain("yarn docs:sync");
    // The original body comes after the header, separated by a blank line.
    expect(out).toMatch(/\n\n# Title$/);
  });
});

describe("hasAutoGeneratedMarker", () => {
  it("detects marker presence", () => {
    expect(hasAutoGeneratedMarker(`<!-- ${AUTO_GEN_MARKER} -->\n# x`)).toBe(true);
    expect(hasAutoGeneratedMarker("# x")).toBe(false);
  });
});
